"""Deterministic KTSL paper-style fixtures."""

from __future__ import annotations

from .models import (
    ActorKnowledgeState,
    BarrierCheckpoint,
    CausalDependency,
    ClueRecord,
    CommitRecord,
    EventRecord,
    InfoLabel,
    KTSLFixture,
    KTSLLocation,
    KeeperTruth,
    SceneCard,
    SceneCoupling,
)

KTSL_FIXTURE_IDS = (
    "library_sewer_church",
    "police_station_hospital_old_house",
)


def build_library_sewer_church_fixture() -> KTSLFixture:
    """Build the library/sewer/church simulated fixture."""

    locations = [
        KTSLLocation(
            id="library",
            name="Library",
            public_summary="A closed municipal library with a restricted archive.",
            keeper_summary="The archive index points to a drainage route under the old chapel.",
            tags=["archive", "entry"],
        ),
        KTSLLocation(
            id="sewer",
            name="Sewer",
            public_summary="A flooded service tunnel below the library block.",
            keeper_summary="A sluice mark confirms the chapel reliquary was moved through the tunnel.",
            tags=["hazard", "transit"],
        ),
        KTSLLocation(
            id="church",
            name="Church",
            public_summary="An abandoned church with fresh wax on the altar rail.",
            keeper_summary="The reliquary contains the mayor's sealed confession.",
            tags=["ritual", "resolution"],
        ),
    ]

    info_labels = [
        InfoLabel(
            id="info_archive_index",
            kind="know",
            scene_id="scene_library",
            payload="Archive shelf B-13 maps the library stacks to the storm drain access.",
            sensitivity="medium",
            public_payload="The archive index mentions a storm drain access.",
            redaction="The archive index references a restricted route.",
            known_by_character_ids=["ada"],
            authorized_character_ids=["ada", "bram"],
            expected_declassified_for_character_ids=["bram"],
            should_declassify=True,
            notes="Expected to move from Ada's know state to Bram before sewer action.",
        ),
        InfoLabel(
            id="info_sewer_sigil",
            kind="obs",
            scene_id="scene_sewer",
            payload="A chalk sigil beside the sluice matches the church floor mosaic.",
            sensitivity="low",
            public_payload="A chalk mark resembles a church pattern.",
            redaction="A chalk mark links two locations.",
            observed_by_player_ids=["p2"],
            authorized_character_ids=["bram", "celia"],
        ),
        InfoLabel(
            id="info_confession",
            kind="know",
            scene_id="scene_church",
            payload="The reliquary hides the mayor's confession naming the cult patron.",
            sensitivity="high",
            public_payload="The reliquary contains a sealed confession.",
            redaction="The reliquary contains a sensitive sealed document.",
            authorized_character_ids=["celia"],
            expected_declassified_for_character_ids=["ada", "bram"],
            should_declassify=True,
        ),
        InfoLabel(
            id="info_church_wax",
            kind="obs",
            scene_id="scene_church",
            payload="The altar wax is warm enough to prove someone was present within ten minutes.",
            sensitivity="low",
            public_payload="The altar wax is still warm.",
            observed_by_player_ids=["p3"],
            authorized_character_ids=["celia"],
        ),
    ]

    keeper_truths = [
        KeeperTruth(
            id="truth_archive_route",
            scene_id="scene_library",
            payload="The library catalog is the only fair route to the sewer sluice.",
            linked_info_ids=["info_archive_index"],
        ),
        KeeperTruth(
            id="truth_reliquary_confession",
            scene_id="scene_church",
            payload="The confession should not become public until the church barrier is satisfied.",
            linked_info_ids=["info_confession"],
        ),
    ]

    clues = [
        ClueRecord(
            id="clue_archive_index",
            scene_id="scene_library",
            info_id="info_archive_index",
            title="Restricted archive index",
            public_hint="The catalog number points below street level.",
            keeper_detail="A successful library action produces info_archive_index.",
            output_info_ids=["info_archive_index"],
        ),
        ClueRecord(
            id="clue_sluice_sigil",
            scene_id="scene_sewer",
            info_id="info_sewer_sigil",
            title="Sluice chalk sigil",
            public_hint="The tunnel mark echoes a church mosaic.",
            keeper_detail="Requires the archive route before it can be interpreted IC.",
            required_info_ids=["info_archive_index"],
            output_info_ids=["info_sewer_sigil"],
        ),
        ClueRecord(
            id="clue_reliquary",
            scene_id="scene_church",
            info_id="info_confession",
            title="Sealed reliquary",
            public_hint="The altar object is newly disturbed.",
            keeper_detail="Opening it before the sewer evidence is a causal violation.",
            required_info_ids=["info_sewer_sigil"],
            output_info_ids=["info_confession"],
        ),
    ]

    barriers = [
        BarrierCheckpoint(
            id="barrier_sewer_entry",
            scene_ids=["library", "sewer"],
            required_event_ids=["evt_library_decode_index"],
            required_info_ids=["info_archive_index"],
            reason="The sewer action should wait for the archive route to be committed.",
        ),
        BarrierCheckpoint(
            id="barrier_church_reveal",
            scene_ids=["sewer", "church"],
            required_event_ids=["evt_sewer_trace_sigil"],
            required_info_ids=["info_sewer_sigil"],
            reason="The confession reveal depends on the sewer sigil observation.",
        ),
    ]

    scenes = [
        SceneCard(
            id="scene_library",
            name="Library archive",
            location_id="library",
            participant_character_ids=["ada"],
            participant_player_ids=["p1"],
            public_summary="Ada researches a restricted catalog entry.",
            keeper_summary="This scene establishes the only authorized sewer route.",
            info_ids=["info_archive_index"],
            clue_ids=["clue_archive_index"],
            keeper_truth_ids=["truth_archive_route"],
            barrier_id="barrier_sewer_entry",
            time_start_minute=0,
            time_end_minute=12,
            spotlight_start_minute=0,
            spotlight_end_minute=12,
            coupling_input_ids=["coupling_library_sewer"],
        ),
        SceneCard(
            id="scene_sewer",
            name="Sewer sluice",
            location_id="sewer",
            participant_character_ids=["bram"],
            participant_player_ids=["p2"],
            public_summary="Bram searches the flooded service tunnel.",
            keeper_summary="The sigil lets the church scene advance without retcon.",
            info_ids=["info_sewer_sigil"],
            clue_ids=["clue_sluice_sigil"],
            barrier_id="barrier_church_reveal",
            time_start_minute=8,
            time_end_minute=20,
            spotlight_start_minute=12,
            spotlight_end_minute=24,
            coupling_input_ids=["coupling_library_sewer", "coupling_sewer_church"],
        ),
        SceneCard(
            id="scene_church",
            name="Abandoned church",
            location_id="church",
            participant_character_ids=["celia"],
            participant_player_ids=["p3"],
            public_summary="Celia examines the altar and reliquary.",
            keeper_summary="The high-sensitivity confession is the fixture's declassification target.",
            info_ids=["info_confession", "info_church_wax"],
            clue_ids=["clue_reliquary"],
            keeper_truth_ids=["truth_reliquary_confession"],
            barrier_id="barrier_church_reveal",
            time_start_minute=16,
            time_end_minute=32,
            spotlight_start_minute=24,
            spotlight_end_minute=40,
            coupling_input_ids=["coupling_sewer_church"],
        ),
    ]

    dependencies = [
        CausalDependency(
            id="dep_sewer_after_library",
            required_event_ids=["evt_library_decode_index"],
            required_info_ids=["info_archive_index"],
            reason="Bram cannot justify the sluice route without Ada's committed archive result.",
        ),
        CausalDependency(
            id="dep_church_after_sewer",
            required_event_ids=["evt_sewer_trace_sigil"],
            required_info_ids=["info_sewer_sigil"],
            reason="Celia cannot identify the reliquary pattern before the sewer sigil is observed.",
        ),
    ]

    events = [
        EventRecord(
            id="evt_library_decode_index",
            scene_id="scene_library",
            action_id="act_decode_archive_index",
            action_text="Decode the restricted archive index.",
            actor="Ada",
            player_id="p1",
            character_id="ada",
            status="committed",
            committed=True,
            commit_index=0,
            output_info_ids=["info_archive_index"],
            public_payload="Ada finds a storm drain reference in the archive.",
            time_start_minute=2,
            time_end_minute=10,
            spotlight_start_minute=0,
            spotlight_end_minute=12,
        ),
        EventRecord(
            id="evt_sewer_trace_sigil",
            scene_id="scene_sewer",
            action_id="act_trace_sluice_sigil",
            action_text="Use the archive route to trace the sluice sigil.",
            actor="Bram",
            player_id="p2",
            character_id="bram",
            status="committed",
            committed=True,
            commit_index=1,
            barrier_id="barrier_sewer_entry",
            required_info_ids=["info_archive_index"],
            observed_info_ids=["info_sewer_sigil"],
            output_info_ids=["info_sewer_sigil"],
            causal_dependency_ids=["dep_sewer_after_library"],
            depends_on_event_ids=["evt_library_decode_index"],
            public_payload="Bram confirms the tunnel points toward the church.",
            time_start_minute=8,
            time_end_minute=19,
            spotlight_start_minute=12,
            spotlight_end_minute=24,
        ),
        EventRecord(
            id="evt_church_open_reliquary",
            scene_id="scene_church",
            action_id="act_open_reliquary",
            action_text="Open the reliquary after matching the sewer sigil.",
            actor="Celia",
            player_id="p3",
            character_id="celia",
            status="proposed",
            barrier_id="barrier_church_reveal",
            required_info_ids=["info_sewer_sigil"],
            observed_info_ids=["info_church_wax"],
            known_info_ids=["info_confession"],
            output_info_ids=["info_confession"],
            causal_dependency_ids=["dep_church_after_sewer"],
            depends_on_event_ids=["evt_sewer_trace_sigil"],
            public_payload="Celia finds a sealed confession in the reliquary.",
            private_payload="The confession names the cult patron.",
            redaction="Celia finds a sensitive sealed document.",
            time_start_minute=24,
            time_end_minute=34,
            spotlight_start_minute=24,
            spotlight_end_minute=40,
        ),
    ]

    couplings = [
        SceneCoupling(
            id="coupling_library_sewer",
            source_scene_id="scene_library",
            target_scene_id="scene_sewer",
            coupling_score=0.82,
            mode="linked",
            condition_type="required_info",
            required_info_ids=["info_archive_index"],
            required_scene_ids=["scene_library"],
            input_event_ids=["evt_library_decode_index"],
            output_info_ids=["info_sewer_sigil"],
            shared_character_ids=["ada", "bram"],
            barrier_id="barrier_sewer_entry",
            barrier_policy="hard",
            expected_drift_minutes=4,
            rationale="The sewer route is causally gated by library knowledge.",
        ),
        SceneCoupling(
            id="coupling_sewer_church",
            source_scene_id="scene_sewer",
            target_scene_id="scene_church",
            coupling_score=0.9,
            mode="locked",
            condition_type="causal_dependency",
            required_info_ids=["info_sewer_sigil"],
            required_scene_ids=["scene_sewer"],
            input_event_ids=["evt_sewer_trace_sigil"],
            output_info_ids=["info_confession"],
            shared_character_ids=["bram", "celia"],
            barrier_id="barrier_church_reveal",
            barrier_policy="hard",
            expected_drift_minutes=8,
            rationale="The church reveal is high coupling and should wait for sewer evidence.",
        ),
    ]

    return KTSLFixture(
        id="library_sewer_church",
        title="Library / Sewer / Church simulated fixture",
        description="A deterministic three-scene fixture for schedule, filter, and coupling comparisons.",
        locations=locations,
        scenes=scenes,
        keeper_truths=keeper_truths,
        info_labels=info_labels,
        clues=clues,
        initial_knowledge=[
            ActorKnowledgeState(
                player_id="p1",
                character_id="ada",
                scene_id="scene_library",
                known_info_ids=["info_archive_index"],
                authorized_info_ids=["info_archive_index"],
            ),
            ActorKnowledgeState(
                player_id="p2",
                character_id="bram",
                scene_id="scene_sewer",
                observed_info_ids=["info_sewer_sigil"],
                authorized_info_ids=["info_archive_index", "info_sewer_sigil"],
                notes="Bram observes the sigil but needs declassified archive knowledge for IC use.",
            ),
            ActorKnowledgeState(
                player_id="p3",
                character_id="celia",
                scene_id="scene_church",
                observed_info_ids=["info_church_wax"],
                authorized_info_ids=["info_church_wax", "info_confession"],
            ),
        ],
        causal_dependencies=dependencies,
        events=events,
        commit_records=[
            CommitRecord(
                id="commit_library_decode_index",
                event_id="evt_library_decode_index",
                scene_id="scene_library",
                status="committed",
                commit_index=0,
                actor="Ada",
            ),
            CommitRecord(
                id="commit_sewer_trace_sigil",
                event_id="evt_sewer_trace_sigil",
                scene_id="scene_sewer",
                status="committed",
                commit_index=1,
                barrier_id="barrier_sewer_entry",
                actor="Bram",
            ),
        ],
        barriers=barriers,
        couplings=couplings,
        expected_declassified_info_ids=["info_archive_index", "info_confession"],
        metadata={"conditions": ["baseline", "schedule_only", "ktsl_full"]},
    )


def build_police_hospital_old_house_fixture() -> KTSLFixture:
    """Build the police station/hospital/old house simulated fixture."""

    locations = [
        KTSLLocation(
            id="police_station",
            name="Police Station",
            public_summary="A records office with sealed missing-person files.",
            keeper_summary="The file timeline contradicts the public accident report.",
            tags=["records", "entry"],
        ),
        KTSLLocation(
            id="hospital",
            name="Hospital",
            public_summary="A night ward with archived medication logs.",
            keeper_summary="The dosage log reveals a staged coma and a false transfer.",
            tags=["medical", "evidence"],
        ),
        KTSLLocation(
            id="old_house",
            name="Old House",
            public_summary="A boarded family house at the edge of town.",
            keeper_summary="The basement contains the hidden patient and the missing ledger.",
            tags=["site", "resolution"],
        ),
    ]

    info_labels = [
        InfoLabel(
            id="info_case_file_timeline",
            kind="know",
            scene_id="scene_police_station",
            payload="The missing-person file timeline leaves a two-hour impossible gap.",
            sensitivity="medium",
            public_payload="The file has an unexplained time gap.",
            redaction="The file contains a restricted timeline inconsistency.",
            known_by_character_ids=["mira"],
            authorized_character_ids=["mira", "noah"],
            expected_declassified_for_character_ids=["noah"],
            should_declassify=True,
        ),
        InfoLabel(
            id="info_hospital_dosage",
            kind="obs",
            scene_id="scene_hospital",
            payload="The dosage log shows sedatives administered after the recorded transfer time.",
            sensitivity="high",
            public_payload="The dosage log conflicts with the transfer time.",
            redaction="The dosage log contains a sensitive medical inconsistency.",
            observed_by_player_ids=["p5"],
            authorized_character_ids=["noah"],
            expected_declassified_for_character_ids=["mira", "iris"],
            should_declassify=True,
        ),
        InfoLabel(
            id="info_house_basement",
            kind="know",
            scene_id="scene_old_house",
            payload="The old house basement is the off-book holding site.",
            sensitivity="high",
            public_payload="The old house may be the hidden site.",
            redaction="The old house connects to a sensitive holding-site clue.",
            authorized_character_ids=["iris"],
            expected_declassified_for_character_ids=["mira", "noah"],
            should_declassify=True,
        ),
        InfoLabel(
            id="info_house_broken_lock",
            kind="obs",
            scene_id="scene_old_house",
            payload="The basement lock was broken from the inside less than an hour ago.",
            sensitivity="low",
            public_payload="The basement lock was recently broken from inside.",
            observed_by_player_ids=["p6"],
            authorized_character_ids=["iris"],
        ),
    ]

    keeper_truths = [
        KeeperTruth(
            id="truth_false_transfer",
            scene_id="scene_hospital",
            payload="The hospital transfer record was forged to hide the old house route.",
            linked_info_ids=["info_hospital_dosage"],
        ),
        KeeperTruth(
            id="truth_hidden_patient",
            scene_id="scene_old_house",
            payload="The missing patient was kept below the old house until the investigators arrived.",
            linked_info_ids=["info_house_basement", "info_house_broken_lock"],
        ),
    ]

    clues = [
        ClueRecord(
            id="clue_case_file_timeline",
            scene_id="scene_police_station",
            info_id="info_case_file_timeline",
            title="Impossible case-file timeline",
            public_hint="The transfer window does not add up.",
            keeper_detail="Starts the hospital coupling path.",
            output_info_ids=["info_case_file_timeline"],
        ),
        ClueRecord(
            id="clue_hospital_dosage",
            scene_id="scene_hospital",
            info_id="info_hospital_dosage",
            title="Medication dosage log",
            public_hint="A dosage appears after the official transfer.",
            keeper_detail="High sensitivity medical payload must be redacted until authorized.",
            required_info_ids=["info_case_file_timeline"],
            output_info_ids=["info_hospital_dosage"],
        ),
        ClueRecord(
            id="clue_house_basement",
            scene_id="scene_old_house",
            info_id="info_house_basement",
            title="Old house basement",
            public_hint="The old house shows signs of recent confinement.",
            keeper_detail="Requires the hospital dosage contradiction before IC accusation.",
            required_info_ids=["info_hospital_dosage"],
            output_info_ids=["info_house_basement"],
        ),
    ]

    barriers = [
        BarrierCheckpoint(
            id="barrier_hospital_records",
            scene_ids=["police_station", "hospital"],
            required_event_ids=["evt_police_reconcile_file"],
            required_info_ids=["info_case_file_timeline"],
            reason="The hospital log should wait for the police timeline gap.",
        ),
        BarrierCheckpoint(
            id="barrier_old_house_entry",
            scene_ids=["hospital", "old_house"],
            required_event_ids=["evt_hospital_read_dosage"],
            required_info_ids=["info_hospital_dosage"],
            reason="The old house accusation depends on the medical contradiction.",
        ),
    ]

    scenes = [
        SceneCard(
            id="scene_police_station",
            name="Police records office",
            location_id="police_station",
            participant_character_ids=["mira"],
            participant_player_ids=["p4"],
            public_summary="Mira audits the sealed missing-person file.",
            keeper_summary="The time gap authorizes the hospital route.",
            info_ids=["info_case_file_timeline"],
            clue_ids=["clue_case_file_timeline"],
            barrier_id="barrier_hospital_records",
            time_start_minute=0,
            time_end_minute=10,
            spotlight_start_minute=0,
            spotlight_end_minute=10,
            coupling_input_ids=["coupling_police_hospital"],
        ),
        SceneCard(
            id="scene_hospital",
            name="Hospital night ward",
            location_id="hospital",
            participant_character_ids=["noah"],
            participant_player_ids=["p5"],
            public_summary="Noah reviews medication logs in the night ward.",
            keeper_summary="The dosage log is high-sensitivity and requires redaction.",
            info_ids=["info_hospital_dosage"],
            clue_ids=["clue_hospital_dosage"],
            keeper_truth_ids=["truth_false_transfer"],
            barrier_id="barrier_old_house_entry",
            time_start_minute=7,
            time_end_minute=22,
            spotlight_start_minute=10,
            spotlight_end_minute=25,
            coupling_input_ids=["coupling_police_hospital", "coupling_hospital_house"],
        ),
        SceneCard(
            id="scene_old_house",
            name="Old family house",
            location_id="old_house",
            participant_character_ids=["iris"],
            participant_player_ids=["p6"],
            public_summary="Iris searches the boarded house.",
            keeper_summary="The basement reveal resolves the false transfer chain.",
            info_ids=["info_house_basement", "info_house_broken_lock"],
            clue_ids=["clue_house_basement"],
            keeper_truth_ids=["truth_hidden_patient"],
            barrier_id="barrier_old_house_entry",
            time_start_minute=18,
            time_end_minute=36,
            spotlight_start_minute=25,
            spotlight_end_minute=43,
            coupling_input_ids=["coupling_hospital_house"],
        ),
    ]

    dependencies = [
        CausalDependency(
            id="dep_hospital_after_police",
            required_event_ids=["evt_police_reconcile_file"],
            required_info_ids=["info_case_file_timeline"],
            reason="Noah needs the police timeline gap to request the right hospital log.",
        ),
        CausalDependency(
            id="dep_house_after_hospital",
            required_event_ids=["evt_hospital_read_dosage"],
            required_info_ids=["info_hospital_dosage"],
            reason="Iris cannot justify the old house accusation without the dosage contradiction.",
        ),
    ]

    events = [
        EventRecord(
            id="evt_police_reconcile_file",
            scene_id="scene_police_station",
            action_id="act_reconcile_case_file",
            action_text="Reconcile the sealed case file timeline.",
            actor="Mira",
            player_id="p4",
            character_id="mira",
            status="committed",
            committed=True,
            commit_index=0,
            output_info_ids=["info_case_file_timeline"],
            public_payload="Mira finds an unexplained gap in the file timeline.",
            time_start_minute=1,
            time_end_minute=9,
            spotlight_start_minute=0,
            spotlight_end_minute=10,
        ),
        EventRecord(
            id="evt_hospital_read_dosage",
            scene_id="scene_hospital",
            action_id="act_read_dosage_log",
            action_text="Use the timeline gap to locate the dosage log.",
            actor="Noah",
            player_id="p5",
            character_id="noah",
            status="committed",
            committed=True,
            commit_index=1,
            barrier_id="barrier_hospital_records",
            required_info_ids=["info_case_file_timeline"],
            observed_info_ids=["info_hospital_dosage"],
            output_info_ids=["info_hospital_dosage"],
            causal_dependency_ids=["dep_hospital_after_police"],
            depends_on_event_ids=["evt_police_reconcile_file"],
            public_payload="Noah finds a dosage conflict in the hospital log.",
            redaction="Noah finds a sensitive inconsistency in the hospital log.",
            time_start_minute=7,
            time_end_minute=21,
            spotlight_start_minute=10,
            spotlight_end_minute=25,
        ),
        EventRecord(
            id="evt_house_identify_basement",
            scene_id="scene_old_house",
            action_id="act_identify_basement_site",
            action_text="Identify the old house basement as the hidden holding site.",
            actor="Iris",
            player_id="p6",
            character_id="iris",
            status="proposed",
            barrier_id="barrier_old_house_entry",
            required_info_ids=["info_hospital_dosage"],
            observed_info_ids=["info_house_broken_lock"],
            known_info_ids=["info_house_basement"],
            output_info_ids=["info_house_basement"],
            causal_dependency_ids=["dep_house_after_hospital"],
            depends_on_event_ids=["evt_hospital_read_dosage"],
            public_payload="Iris links the basement to the hidden patient route.",
            private_payload="The basement was used as an off-book holding site.",
            redaction="Iris links the basement to a sensitive holding-site clue.",
            time_start_minute=26,
            time_end_minute=35,
            spotlight_start_minute=25,
            spotlight_end_minute=43,
        ),
    ]

    couplings = [
        SceneCoupling(
            id="coupling_police_hospital",
            source_scene_id="scene_police_station",
            target_scene_id="scene_hospital",
            coupling_score=0.78,
            mode="linked",
            condition_type="required_info",
            required_info_ids=["info_case_file_timeline"],
            required_scene_ids=["scene_police_station"],
            input_event_ids=["evt_police_reconcile_file"],
            output_info_ids=["info_hospital_dosage"],
            shared_character_ids=["mira", "noah"],
            barrier_id="barrier_hospital_records",
            barrier_policy="hard",
            expected_drift_minutes=5,
            rationale="The hospital log is only meaningful after the police timeline gap.",
        ),
        SceneCoupling(
            id="coupling_hospital_house",
            source_scene_id="scene_hospital",
            target_scene_id="scene_old_house",
            coupling_score=0.88,
            mode="locked",
            condition_type="causal_dependency",
            required_info_ids=["info_hospital_dosage"],
            required_scene_ids=["scene_hospital"],
            input_event_ids=["evt_hospital_read_dosage"],
            output_info_ids=["info_house_basement"],
            shared_character_ids=["noah", "iris"],
            barrier_id="barrier_old_house_entry",
            barrier_policy="hard",
            expected_drift_minutes=7,
            rationale="The old house reveal should wait for the high-sensitivity medical contradiction.",
        ),
    ]

    return KTSLFixture(
        id="police_station_hospital_old_house",
        title="Police Station / Hospital / Old House simulated fixture",
        description="A deterministic three-scene fixture with high-sensitivity medical and location payloads.",
        locations=locations,
        scenes=scenes,
        keeper_truths=keeper_truths,
        info_labels=info_labels,
        clues=clues,
        initial_knowledge=[
            ActorKnowledgeState(
                player_id="p4",
                character_id="mira",
                scene_id="scene_police_station",
                known_info_ids=["info_case_file_timeline"],
                authorized_info_ids=["info_case_file_timeline"],
            ),
            ActorKnowledgeState(
                player_id="p5",
                character_id="noah",
                scene_id="scene_hospital",
                observed_info_ids=["info_hospital_dosage"],
                authorized_info_ids=["info_case_file_timeline", "info_hospital_dosage"],
                notes="Noah observes medical data; public output should use redaction until declassified.",
            ),
            ActorKnowledgeState(
                player_id="p6",
                character_id="iris",
                scene_id="scene_old_house",
                observed_info_ids=["info_house_broken_lock"],
                authorized_info_ids=["info_house_broken_lock", "info_house_basement"],
            ),
        ],
        causal_dependencies=dependencies,
        events=events,
        commit_records=[
            CommitRecord(
                id="commit_police_reconcile_file",
                event_id="evt_police_reconcile_file",
                scene_id="scene_police_station",
                status="committed",
                commit_index=0,
                actor="Mira",
            ),
            CommitRecord(
                id="commit_hospital_read_dosage",
                event_id="evt_hospital_read_dosage",
                scene_id="scene_hospital",
                status="committed",
                commit_index=1,
                barrier_id="barrier_hospital_records",
                actor="Noah",
            ),
        ],
        barriers=barriers,
        couplings=couplings,
        expected_declassified_info_ids=[
            "info_case_file_timeline",
            "info_hospital_dosage",
            "info_house_basement",
        ],
        metadata={"conditions": ["baseline", "schedule_only", "ktsl_full"]},
    )


def list_ktsl_fixtures() -> list[KTSLFixture]:
    """Return fresh deterministic fixture objects."""

    return [
        build_library_sewer_church_fixture(),
        build_police_hospital_old_house_fixture(),
    ]


def get_ktsl_fixture(fixture_id: str) -> KTSLFixture:
    """Return one deterministic fixture by id."""

    for fixture in list_ktsl_fixtures():
        if fixture.id == fixture_id:
            return fixture
    raise KeyError(f"Unknown KTSL fixture id: {fixture_id}")
